### ISSUE TITLE
NullPointerException at me.teakivy.eggfix.Main.onCommand(Main.java:66) ~[?:?]

### ISSUE THREAD

**Issue by rcchatters** [teakivy/EggFix-1.17#1]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Paper-83]

Occurred when /eggfix command was issued by the Admin. Can you confirm that this plug-in is intended to work with Paper?

Does this method require the exact world name or is "world" sufficient?

@Nullable World getWorld​(@NotNull
 @NotNull String name)
Gets the world with the given name.
Parameters:
name - the name of the world to retrieve
Returns:
a world with the given name, or null if none exists

**Comment by teakivy** [comment]
This is fixed in [Release 1.1.1](https://github.com/teakivy/EggFix-1.17/releases/tag/1.1.1)
The method now gets what world the player is currently in.

**Comment by rcchatters** [comment]
Thank you very much teakivy. I tested the plug-in our Paper 1.17.1 server, "RiverStyx", and it did not throw an exception, reported:
"Removed 2 Mobs Holding Eggs"
